In [1]:
import gym
import numpy as np
import time
%matplotlib inline
import matplotlib.pyplot as plt
import random


In [2]:
env = gym.make("CartPole-v1")
print(env.observation_space)
print(env.action_space)

Box(4,)
Discrete(2)


In [3]:

class No_Learning_Agent():
    def __init__(self,env):
        self.act_size = env.action_space.n
        print("action size",self.act_size)
    
    def get_action(self,state):
        #action = random.choice(range(self.act_size))                                                                                                                                       
        pole_angle = state[2]
        if pole_angle < 0:
            action = 0
        else:
            action = 1
        return action

In [5]:
agent = No_Learning_Agent(env)

no_of_episodes = 100
rewards_list = []
for x in range(no_of_episodes):
    reward1 = 0
    state = env.reset()
    print(state)
    for i in range(200):
        #action = env.action_space.sample()
        action = agent.get_action(state)
        state, reward, done, info = env.step(action)
        print("step = ",i,", state = ",state)
        reward1 = reward1 + reward
        #env.render()
        #time.sleep(0.05)
        if done == True:
            #print (i)
            #print(state)
            #print(reward)
            #print(reward1)
            rewards_list.append(reward1)
            break
print("Average reward over ",no_of_episodes," episodes = ",np.average(rewards_list))
print("Max reward in an episode over ",no_of_episodes," episodes = ",np.max(rewards_list))
print("Min reward in an episode over",no_of_episodes," episodes = ",np.min(rewards_list))
    

action size 2
[0.0453819  0.04449897 0.02845532 0.03790462]
step =  0 , state =  [ 0.04627188  0.23920155  0.02921341 -0.2456663 ]
step =  1 , state =  [ 0.05105591  0.43389435  0.02430008 -0.52899336]
step =  2 , state =  [ 0.0597338   0.62866615  0.01372022 -0.8139213 ]
step =  3 , state =  [ 0.07230712  0.82359755 -0.00255821 -1.10225724]
step =  4 , state =  [ 0.08877907  0.62850934 -0.02460336 -0.81037801]
step =  5 , state =  [ 0.10134926  0.43373296 -0.04081092 -0.52553452]
step =  6 , state =  [ 0.11002392  0.23920835 -0.05132161 -0.24598563]
step =  7 , state =  [ 0.11480808  0.04485553 -0.05624132  0.03007782]
step =  8 , state =  [ 0.11570519 -0.14941667 -0.05563976  0.30449914]
step =  9 , state =  [ 0.11271686 -0.34370338 -0.04954978  0.57912856]
step =  10 , state =  [ 0.10584279 -0.53809719 -0.03796721  0.85579972]
step =  11 , state =  [ 0.09508085 -0.73268177 -0.02085121  1.13630656]
step =  12 , state =  [ 0.08042721 -0.92752484  0.00187492  1.42237782]
step =  13 , s

step =  30 , state =  [-0.17288775  0.1918545   0.14383678 -0.26827902]
step =  31 , state =  [-0.16905066  0.38466215  0.1384712  -0.51236155]
step =  32 , state =  [-0.16135742  0.57758991  0.12822397 -0.75840262]
step =  33 , state =  [-0.14980562  0.7707337   0.11305592 -1.00814528]
step =  34 , state =  [-0.13439094  0.96417976  0.09289301 -1.26329424]
step =  35 , state =  [-0.11510735  1.15799954  0.06762712 -1.52549916]
step =  36 , state =  [-0.09194736  1.3522431   0.03711714 -1.79633125]
step =  37 , state =  [-6.49024954e-02  1.54693043e+00  1.19051645e-03 -2.07725118e+00]
step =  38 , state =  [-0.03396389  1.7420403  -0.04035451 -2.36956576]
step =  39 , state =  [ 8.76919027e-04  1.54729865e+00 -8.77458223e-02 -2.08955212e+00]
step =  40 , state =  [ 0.03182289  1.35316445 -0.12953686 -1.8252353 ]
step =  41 , state =  [ 0.05888618  1.1596959  -0.16604157 -1.57544127]
step =  42 , state =  [ 0.0820801   0.96689685 -0.1975504  -1.33881234]
step =  43 , state =  [ 0.101418

step =  4 , state =  [ 0.06832061  0.57121624 -0.03620621 -0.88393585]
step =  5 , state =  [ 0.07974494  0.37660415 -0.05388492 -0.60285133]
step =  6 , state =  [ 0.08727702  0.18227564 -0.06594195 -0.32761616]
step =  7 , state =  [ 0.09092253 -0.01184857 -0.07249427 -0.05643559]
step =  8 , state =  [ 0.09068556 -0.20586024 -0.07362298  0.21252289]
step =  9 , state =  [ 0.08656836 -0.39985658 -0.06937253  0.4811035 ]
step =  10 , state =  [ 0.07857123 -0.59393423 -0.05975046  0.75114059]
step =  11 , state =  [ 0.06669254 -0.7881835  -0.04472764  1.02443834]
step =  12 , state =  [ 0.05092887 -0.98268217 -0.02423888  1.30274903]
step =  13 , state =  [ 0.03127523 -1.1774884   0.0018161   1.587747  ]
step =  14 , state =  [ 0.00772546 -0.98238807  0.03357104  1.29563093]
step =  15 , state =  [-0.0119223  -0.7877083   0.05948366  1.01364384]
step =  16 , state =  [-0.02767647 -0.59342806  0.07975654  0.74021679]
step =  17 , state =  [-0.03954503 -0.39949258  0.09456087  0.47366188

step =  42 , state =  [-0.21655044 -1.36538282  0.12887205  1.50658041]
step =  43 , state =  [-0.24385809 -1.17203776  0.15900365  1.25675139]
step =  44 , state =  [-0.26729885 -0.97926755  0.18413868  1.01779395]
step =  45 , state =  [-0.2868842  -0.78701369  0.20449456  0.7881198 ]
step =  46 , state =  [-0.30262447 -0.59519914  0.22025696  0.56609627]
[ 0.03887565  0.02634497 -0.04478625  0.02156504]
step =  0 , state =  [ 0.03940255 -0.16810704 -0.04435495  0.29978782]
step =  1 , state =  [ 0.03604041 -0.36256962 -0.03835919  0.57815873]
step =  2 , state =  [ 0.02878902 -0.55713355 -0.02679602  0.8585151 ]
step =  3 , state =  [ 0.01764635 -0.75188043 -0.00962572  1.14265346]
step =  4 , state =  [ 0.00260874 -0.94687528  0.01322735  1.43230227]
step =  5 , state =  [-0.01632877 -0.75191903  0.0418734   1.14378221]
step =  6 , state =  [-0.03136715 -0.55736842  0.06474904  0.86451928]
step =  7 , state =  [-0.04251452 -0.36318478  0.08203943  0.5928771 ]
step =  8 , state =  [

step =  25 , state =  [ 0.08882143 -0.40120359 -0.15199242  0.459737  ]
step =  26 , state =  [ 0.08079735 -0.59388718 -0.14279768  0.7009164 ]
step =  27 , state =  [ 0.06891961 -0.7867713  -0.12877935  0.94545776]
step =  28 , state =  [ 0.05318418 -0.97994559 -0.1098702   1.19506323]
step =  29 , state =  [ 0.03358527 -1.17348701 -0.08596893  1.45138798]
step =  30 , state =  [ 0.01011553 -1.36745393 -0.05694117  1.71602013]
step =  31 , state =  [-0.01723355 -1.56187845 -0.02262077  1.99045259]
step =  32 , state =  [-0.04847112 -1.75675623  0.01718828  2.27604453]
step =  33 , state =  [-0.08360624 -1.56179808  0.06270917  1.98870361]
step =  34 , state =  [-0.1148422  -1.36738718  0.10248324  1.71608487]
step =  35 , state =  [-0.14218995 -1.17357921  0.13680494  1.45697558]
step =  36 , state =  [-0.16566153 -0.98037535  0.16594445  1.20997281]
step =  37 , state =  [-0.18526904 -0.7877385   0.19014391  0.97355104]
step =  38 , state =  [-0.20102381 -0.59560565  0.20961493  0.74

step =  46 , state =  [-0.01995216 -1.68615603  0.05235582  2.09818135]
step =  47 , state =  [-0.05367529 -1.49159778  0.09431945  1.82212946]
step =  48 , state =  [-0.08350724 -1.29764132  0.13076203  1.56017673]
step =  49 , state =  [-0.10946007 -1.10430425  0.16196557  1.31098152]
step =  50 , state =  [-0.13154615 -0.91156106  0.1881852   1.07306057]
step =  51 , state =  [-0.14977737 -0.71935673  0.20964641  0.8448445 ]
[-0.00258771 -0.00705114 -0.03683016 -0.0074814 ]
step =  0 , state =  [-0.00272873 -0.20162607 -0.03697979  0.27335745]
step =  1 , state =  [-0.00676125 -0.39620139 -0.03151264  0.55415132]
step =  2 , state =  [-0.01468528 -0.59086701 -0.02042961  0.83674158]
step =  3 , state =  [-0.02650262 -0.78570405 -0.00369478  1.12293028]
step =  4 , state =  [-0.0422167  -0.98077737  0.01876382  1.41445199]
step =  5 , state =  [-0.06183225 -0.78589285  0.04705286  1.12769291]
step =  6 , state =  [-0.07755011 -0.59141784  0.06960672  0.85013169]
step =  7 , state =  

step =  2 , state =  [-0.0057449   0.62596914  0.00703692 -0.8274032 ]
step =  3 , state =  [ 0.00677448  0.82099417 -0.00951114 -1.11786466]
step =  4 , state =  [ 0.02319437  0.62599831 -0.03186843 -0.82818033]
step =  5 , state =  [ 0.03571433  0.43132623 -0.04843204 -0.54568822]
step =  6 , state =  [ 0.04434086  0.23691705 -0.05934581 -0.26864985]
step =  7 , state =  [ 0.0490792   0.04269003 -0.0647188   0.00474037]
step =  8 , state =  [ 0.049933   -0.15144694 -0.064624    0.27632212]
step =  9 , state =  [ 0.04690406 -0.34559023 -0.05909755  0.54794294]
step =  10 , state =  [ 0.03999226 -0.53983433 -0.04813869  0.82143587]
step =  11 , state =  [ 0.02919557 -0.7342657  -0.03170998  1.09859776]
step =  12 , state =  [ 0.01451025 -0.9289562  -0.00973802  1.38116553]
step =  13 , state =  [-0.00406887 -1.12395527  0.01788529  1.67078733]
step =  14 , state =  [-0.02654797 -0.92904562  0.05130104  1.38372761]
step =  15 , state =  [-0.04512889 -0.73459974  0.07897559  1.1075184 ]


step =  42 , state =  [ 0.12805734  1.31320961 -0.16696207 -1.66355465]
step =  43 , state =  [ 0.15432153  1.12037888 -0.20023316 -1.42718986]
step =  44 , state =  [ 0.17672911  0.92821342 -0.22877696 -1.20317678]
[-0.00907407 -0.00290662 -0.00713505 -0.03218693]
step =  0 , state =  [-0.0091322  -0.19792553 -0.00777879  0.2582363 ]
step =  1 , state =  [-0.01309071 -0.39293557 -0.00261406  0.54845557]
step =  2 , state =  [-0.02094942 -0.5880207   0.00835505  0.84031373]
step =  3 , state =  [-0.03270984 -0.3930138   0.02516133  0.55026996]
step =  4 , state =  [-0.04057011 -0.19825414  0.03616672  0.26561958]
step =  5 , state =  [-0.0445352  -0.00366655  0.04147912 -0.01544023]
step =  6 , state =  [-0.04460853  0.19083675  0.04117031 -0.29475287]
step =  7 , state =  [-0.04079179  0.38534831  0.03527525 -0.57417231]
step =  8 , state =  [-0.03308483  0.57995841  0.02379181 -0.85553709]
step =  9 , state =  [-0.02148566  0.7747482   0.00668107 -1.14064495]
step =  10 , state =  [-

step =  26 , state =  [-0.06734581  0.92724094  0.14148941 -1.08100272]
step =  27 , state =  [-0.04880099  1.12024064  0.11986936 -1.32615009]
step =  28 , state =  [-0.02639618  1.3136627   0.09334636 -1.57904401]
step =  29 , state =  [-1.22928280e-04  1.50755717e+00  6.17654775e-02 -1.84121551e+00]
step =  30 , state =  [ 0.03002822  1.70194552  0.02494117 -2.11409452]
step =  31 , state =  [ 0.06406713  1.8968098  -0.01734072 -2.39896809]
step =  32 , state =  [ 0.10200332  1.70184342 -0.06532008 -2.11166041]
step =  33 , state =  [ 0.13604019  1.50743224 -0.10755329 -1.83985599]
step =  34 , state =  [ 0.16618883  1.31364977 -0.14435041 -1.58242162]
step =  35 , state =  [ 0.19246183  1.12051039 -0.17599885 -1.33801744]
step =  36 , state =  [ 0.21487204  0.92798677 -0.20275919 -1.10517006]
step =  37 , state =  [ 0.23343177  0.73602326 -0.2248626  -0.88232705]
[ 0.04130749 -0.0299145  -0.00784346 -0.03410572]
step =  0 , state =  [ 0.0407092  -0.2249231  -0.00852557  0.25609223]

step =  2 , state =  [-0.05681369 -0.54391305 -0.03164485  0.79624842]
step =  3 , state =  [-0.06769195 -0.73858678 -0.01571988  1.07881079]
step =  4 , state =  [-0.08246368 -0.93349764  0.00585633  1.36651951]
step =  5 , state =  [-0.10113364 -0.7384495   0.03318672  1.07567407]
step =  6 , state =  [-0.11590263 -0.54378137  0.0547002   0.79358776]
step =  7 , state =  [-0.12677825 -0.34945125  0.07057196  0.5186024 ]
step =  8 , state =  [-0.13376728 -0.15539015  0.08094401  0.24896626]
step =  9 , state =  [-0.13687508  0.03848816  0.08592333 -0.01712744]
step =  10 , state =  [-0.13610532  0.2322795   0.08558078 -0.28151168]
step =  11 , state =  [-0.13145973  0.42608308  0.07995055 -0.54602308]
step =  12 , state =  [-0.12293807  0.61999603  0.06903009 -0.81248294]
step =  13 , state =  [-0.11053815  0.81410798  0.05278043 -1.08267868]
step =  14 , state =  [-0.09425599  1.00849513  0.03112686 -1.35834312]
step =  15 , state =  [-0.07408608  1.20321319  0.00395999 -1.6411289 ]


step =  35 , state =  [ 0.19858259  1.12242806 -0.17871006 -1.35139684]
step =  36 , state =  [ 0.22103115  0.92994317 -0.205738   -1.11952937]
step =  37 , state =  [ 0.23963001  0.73802551 -0.22812858 -0.8977852 ]
[ 0.02117601  0.03013144  0.003735   -0.00573961]
step =  0 , state =  [ 0.02177863  0.22519962  0.0036202  -0.29724177]
step =  1 , state =  [ 0.02628263  0.42026978 -0.00232463 -0.58878075]
step =  2 , state =  [ 0.03468802  0.22518046 -0.01410025 -0.296831  ]
step =  3 , state =  [ 0.03919163  0.03026232 -0.02003687 -0.00862819]
step =  4 , state =  [ 0.03979688 -0.16456663 -0.02020943  0.27766612]
step =  5 , state =  [ 0.03650555 -0.35939452 -0.01465611  0.56390712]
step =  6 , state =  [ 0.02931765 -0.5543078  -0.00337797  0.85193689]
step =  7 , state =  [ 0.0182315  -0.74938353  0.01366077  1.14355571]
step =  8 , state =  [ 0.00324383 -0.55444271  0.03653189  0.85518789]
step =  9 , state =  [-0.00784503 -0.35983714  0.05363564  0.5742123 ]
step =  10 , state =  [-

step =  48 , state =  [-0.00221214 -1.77807089 -0.05994661  1.99767074]
step =  49 , state =  [-0.03777356 -1.97251736 -0.0199932   2.27120279]
step =  50 , state =  [-0.07722391 -2.16744756  0.02543086  2.55766205]
step =  51 , state =  [-0.12057286 -1.97253711  0.0765841   2.27286677]
step =  52 , state =  [-0.1600236  -1.77820683  0.12204143  2.00471948]
step =  53 , state =  [-0.19558774 -1.58455048  0.16213582  1.75218671]
step =  54 , state =  [-0.22727875 -1.39159765  0.19717956  1.51401276]
step =  55 , state =  [-0.2551107  -1.19933262  0.22745981  1.28879936]
[-0.02832591 -0.0326605   0.03384931  0.0262805 ]
step =  0 , state =  [-0.02897912  0.16196009  0.03437492 -0.25553336]
step =  1 , state =  [-0.02573992  0.35657481  0.02926425 -0.53717875]
step =  2 , state =  [-0.01860842  0.55127335  0.01852068 -0.82049905]
step =  3 , state =  [-0.00758295  0.74613702  0.0021107  -1.10729966]
step =  4 , state =  [ 0.00733979  0.94123116 -0.0200353  -1.39931967]
step =  5 , state =

step =  12 , state =  [ 0.06509448 -0.55879782 -0.07054494  0.79652988]
step =  13 , state =  [ 0.05391852 -0.75288448 -0.05461435  1.06621273]
step =  14 , state =  [ 0.03886084 -0.94724291 -0.03329009  1.34126705]
step =  15 , state =  [ 0.01991598 -1.14193042 -0.00646475  1.62335103]
step =  16 , state =  [-0.00292263 -1.33697568  0.02600227  1.91401219]
step =  17 , state =  [-0.02966215 -1.14214319  0.06428251  1.62950605]
step =  18 , state =  [-0.05250501 -0.94783286  0.09687263  1.3575286 ]
step =  19 , state =  [-0.07146167 -0.75405028  0.12402321  1.09665358]
step =  20 , state =  [-0.08654267 -0.56076011  0.14595628  0.84531474]
step =  21 , state =  [-0.09775787 -0.36789889  0.16286257  0.60185782]
step =  22 , state =  [-0.10511585 -0.17538458  0.17489973  0.36457783]
step =  23 , state =  [-0.10862354  0.01687649  0.18219129  0.13174468]
step =  24 , state =  [-0.10828601  0.20898461  0.18482618 -0.09837973]
step =  25 , state =  [-0.10410632  0.40104295  0.18285858 -0.32

step =  0 , state =  [ 0.0402288   0.21818     0.03958531 -0.28462416]
step =  1 , state =  [ 0.0445924   0.41271566  0.03389283 -0.56456402]
step =  2 , state =  [ 0.05284671  0.6073461   0.02260155 -0.84637942]
step =  3 , state =  [ 0.06499363  0.80215254  0.00567396 -1.13187015]
step =  4 , state =  [ 0.08103668  0.99719975 -0.01696344 -1.42276813]
step =  5 , state =  [ 0.10098068  0.80229163 -0.04541881 -1.13543503]
step =  6 , state =  [ 0.11702651  0.60779239 -0.06812751 -0.85733557]
step =  7 , state =  [ 0.12918236  0.41366148 -0.08527422 -0.58682871]
step =  8 , state =  [ 0.13745559  0.21983083 -0.09701079 -0.32217946]
step =  9 , state =  [ 0.14185221  0.02621455 -0.10345438 -0.06159702]
step =  10 , state =  [ 0.1423765  -0.16728367 -0.10468632  0.19673709]
step =  11 , state =  [ 0.13903082 -0.36076457 -0.10075158  0.45464801]
step =  12 , state =  [ 0.13181553 -0.55432836 -0.09165862  0.71395042]
step =  13 , state =  [ 0.12072897 -0.74806989 -0.07737961  0.9764329 ]
st

step =  24 , state =  [ 0.05548783  0.95828565 -0.07089364 -1.25842989]
step =  25 , state =  [ 0.07465355  0.76413885 -0.09606224 -0.98876649]
step =  26 , state =  [ 0.08993632  0.57042502 -0.11583757 -0.72773429]
step =  27 , state =  [ 0.10134482  0.3770788  -0.13039225 -0.4736387 ]
step =  28 , state =  [ 0.1088864   0.18401611 -0.13986503 -0.22472981]
step =  29 , state =  [ 0.11256672 -0.00885862 -0.14435962  0.02077071]
step =  30 , state =  [ 0.11238955 -0.20164701 -0.14394421  0.26465081]
step =  31 , state =  [ 0.10835661 -0.39445249 -0.13865119  0.50869441]
step =  32 , state =  [ 0.10046756 -0.58737662 -0.1284773   0.75467049]
step =  33 , state =  [ 0.08872003 -0.78051543 -0.11338389  1.00432247]
step =  34 , state =  [ 0.07310972 -0.97395534 -0.09329744  1.25935571]
step =  35 , state =  [ 0.05363061 -1.16776809 -0.06811033  1.52142081]
step =  36 , state =  [ 0.03027525 -1.36200412 -0.03768191  1.79209036]
step =  37 , state =  [ 3.03516750e-03 -1.55668399e+00 -1.840106

step =  38 , state =  [ 0.06213651  1.79267029 -0.03335732 -2.33756463]
step =  39 , state =  [ 0.09798992  1.59786444 -0.08010861 -2.05532365]
step =  40 , state =  [ 0.12994721  1.40364766 -0.12121508 -1.78845949]
step =  41 , state =  [ 0.15802016  1.21007688 -0.15698427 -1.53578387]
step =  42 , state =  [ 0.1822217   1.01715479 -0.18769995 -1.29592324]
step =  43 , state =  [ 0.20256479  0.82484617 -0.21361842 -1.06738719]
[-0.03303441 -0.03402102 -0.01488275 -0.03591506]
step =  0 , state =  [-0.03371483 -0.22892643 -0.01560105  0.25203529]
step =  1 , state =  [-0.03829336 -0.42382217 -0.01056035  0.53975681]
step =  2 , state =  [-4.67698010e-02 -6.18794090e-01  2.34789899e-04  8.29093699e-01]
step =  3 , state =  [-0.05914568 -0.42367535  0.01681666  0.53648462]
step =  4 , state =  [-0.06761919 -0.22879384  0.02754636  0.24914756]
step =  5 , state =  [-0.07219507 -0.03407588  0.03252931 -0.03472096]
step =  6 , state =  [-0.07287658  0.16056485  0.03183489 -0.31696568]
step 

step =  52 , state =  [ 0.19352523  1.77718558 -0.12251509 -2.01768991]
step =  53 , state =  [ 0.22906894  1.58352939 -0.16286889 -1.76531237]
step =  54 , state =  [ 0.26073953  1.39058034 -0.19817514 -1.52739103]
step =  55 , state =  [ 0.28855113  1.19832386 -0.22872296 -1.3025336 ]
[-0.0249792  -0.00920561 -0.02543195  0.03579144]
step =  0 , state =  [-0.02516331 -0.20395381 -0.02471612  0.32034308]
step =  1 , state =  [-0.02924238 -0.39871521 -0.01830926  0.60513015]
step =  2 , state =  [-0.03721669 -0.5935764  -0.00620666  0.89199033]
step =  3 , state =  [-0.04908822 -0.78861361  0.01163315  1.18271576]
step =  4 , state =  [-0.06486049 -0.59364453  0.03528746  0.893702  ]
step =  5 , state =  [-0.07673338 -0.39901847  0.0531615   0.61231701]
step =  6 , state =  [-0.08471375 -0.20467821  0.06540784  0.33684057]
step =  7 , state =  [-0.08880731 -0.01054508  0.07214466  0.06547976]
step =  8 , state =  [-0.08901821  0.18347234  0.07345425 -0.20359719]
step =  9 , state =  [-

step =  7 , state =  [ 0.0682811  -0.01568543 -0.07403883 -0.06998596]
step =  8 , state =  [ 0.06796739 -0.20967212 -0.07543855  0.19844936]
step =  9 , state =  [ 0.06377395 -0.40363855 -0.07146956  0.46641361]
step =  10 , state =  [ 0.05570118 -0.59768176 -0.06214129  0.73574121]
step =  11 , state =  [ 0.04374754 -0.7918928  -0.04742646  1.00823771]
step =  12 , state =  [ 0.02790969 -0.98635064 -0.02726171  1.28565834]
step =  13 , state =  [ 8.18267266e-03 -1.18111518e+00 -1.54854212e-03  1.56968264e+00]
step =  14 , state =  [-0.01543963 -1.37621862  0.02984511  1.86188217]
step =  15 , state =  [-0.042964   -1.1814362   0.06708275  1.57861182]
step =  16 , state =  [-0.06659273 -0.98717433  0.09865499  1.30758196]
step =  17 , state =  [-0.08633621 -0.7934313   0.12480663  1.04733806]
step =  18 , state =  [-0.10220484 -0.60016665  0.14575339  0.79629393]
step =  19 , state =  [-0.11420817 -0.40731335  0.16167927  0.55278122]
step =  20 , state =  [-0.12235444 -0.21478698  0.1

step =  13 , state =  [-0.00621201  1.2017061  -0.01557357 -1.66219451]
step =  14 , state =  [ 0.01782211  1.00676895 -0.04881746 -1.37440267]
step =  15 , state =  [ 0.03795749  0.81228995 -0.07630551 -1.09737835]
step =  16 , state =  [ 0.05420329  0.61825104 -0.09825308 -0.82957897]
step =  17 , state =  [ 0.06656831  0.42459961 -0.11484466 -0.56934274]
step =  18 , state =  [ 0.0750603   0.23125979 -0.12623151 -0.31493357]
step =  19 , state =  [ 0.0796855   0.0381408  -0.13253018 -0.06457353]
step =  20 , state =  [ 0.08044832 -0.1548566  -0.13382165  0.18353399]
step =  21 , state =  [ 0.07735118 -0.34783521 -0.13015097  0.43118759]
step =  22 , state =  [ 0.07039448 -0.54089721 -0.12152722  0.68017485]
step =  23 , state =  [ 0.05957654 -0.7341403  -0.10792372  0.93226052]
step =  24 , state =  [ 0.04489373 -0.92765351 -0.08927851  1.18917349]
step =  25 , state =  [ 0.02634066 -1.12151212 -0.06549504  1.45259026]
step =  26 , state =  [ 0.00391042 -1.3157713  -0.03644324  1.72

step =  4 , state =  [ 0.00915672  0.58050905 -0.03691242 -0.82934815]
step =  5 , state =  [ 0.0207669   0.38591063 -0.05349938 -0.54849914]
step =  6 , state =  [ 0.02848511  0.19157944 -0.06446936 -0.27314072]
step =  7 , state =  [ 0.0323167  -0.00256622 -0.06993218 -0.0014681 ]
step =  8 , state =  [ 0.03226538 -0.19661918 -0.06996154  0.26835657]
step =  9 , state =  [ 0.02833299 -0.39067657 -0.06459441  0.53817866]
step =  10 , state =  [ 0.02051946 -0.58483377 -0.05383083  0.80982952]
step =  11 , state =  [ 0.00882278 -0.77917845 -0.03763424  1.08510566]
step =  12 , state =  [-0.00676078 -0.97378425 -0.01593213  1.3657458 ]
step =  13 , state =  [-0.02623647 -1.16870312  0.01138279  1.65340315]
step =  14 , state =  [-0.04961053 -0.97371589  0.04445085  1.36428772]
step =  15 , state =  [-0.06908485 -0.77917801  0.0717366   1.08583338]
step =  16 , state =  [-0.08466841 -0.58507185  0.09345327  0.81649548]
step =  17 , state =  [-0.09636985 -0.39134511  0.10978318  0.55460867

step =  28 , state =  [ 0.07119504 -0.9750584  -0.06608086  1.28896809]
step =  29 , state =  [ 0.05169387 -1.16928048 -0.0403015   1.56025172]
step =  30 , state =  [ 0.02830826 -1.36389765 -0.00909646  1.840095  ]
step =  31 , state =  [ 1.03030901e-03 -1.55891802e+00  2.77054373e-02  2.12993913e+00]
step =  32 , state =  [-0.03014805 -1.36408153  0.07030422  1.84594092]
step =  33 , state =  [-0.05742968 -1.16980115  0.10722304  1.57589266]
step =  34 , state =  [-0.0808257  -0.9761082   0.13874089  1.31848498]
step =  35 , state =  [-0.10034787 -0.78298628  0.16511059  1.07224477]
step =  36 , state =  [-0.11600759 -0.5903858   0.18655549  0.83559531]
step =  37 , state =  [-0.12781531 -0.39823501  0.20326739  0.60689988]
step =  38 , state =  [-0.13578001 -0.20644791  0.21540539  0.38449187]
Average reward over  100  episodes =  42.33
Max reward in an episode over  100  episodes =  68.0
Min reward in an episode over 100  episodes =  24.0
