In [2]:
import gym
import numpy as np
import time
%matplotlib inline
import matplotlib.pyplot as plt
import random


In [3]:
env = gym.make("CartPole-v1")
print(env.observation_space)
print(env.action_space)

Box(4,)
Discrete(2)


In [4]:

class No_Learning_Agent():
    def __init__(self,env):
        self.act_size = env.action_space.n
        print("action size",self.act_size)
    
    def get_action(self,state):
        action = random.choice(range(self.act_size))                                                                                                                                       
        pole_angle = state[2]
        if pole_angle < 0:
            action = 0
        else:
            action = 1
        return action

In [5]:
agent = No_Learning_Agent(env)

no_of_episodes = 100
rewards_list = []
for x in range(no_of_episodes):
    reward1 = 0
    state = env.reset()
    print(state)
    for i in range(200):
        #action = env.action_space.sample()
        action = agent.get_action(state)
        state, reward, done, info = env.step(action)
        print("step = ",i,", state = ",state)
        reward1 = reward1 + reward
        #env.render()
        #time.sleep(0.05)
        if done == True:
            #print (i)
            #print(state)
            #print(reward)
            #print(reward1)
            rewards_list.append(reward1)
            break
print("Average reward over ",no_of_episodes," episodes = ",np.average(rewards_list))
print("Max reward in an episode over ",no_of_episodes," episodes = ",np.max(rewards_list))
print("Min reward in an episode over",no_of_episodes," episodes = ",np.min(rewards_list))
    

action size 2
[ 0.04600658 -0.01070051  0.03378639  0.02651439]
step =  0 , state =  [ 0.04579257  0.18392103  0.03431668 -0.25532001]
step =  1 , state =  [ 0.04947099  0.37853664  0.02921028 -0.53698442]
step =  2 , state =  [ 0.05704173  0.57323597  0.01847059 -0.82032224]
step =  3 , state =  [ 0.06850645  0.76810035  0.00206415 -1.1071389 ]
step =  4 , state =  [ 0.08386845  0.96319511 -0.02007863 -1.39917356]
step =  5 , state =  [ 0.10313236  0.76832844 -0.0480621  -1.11283519]
step =  6 , state =  [ 0.11849892  0.5738695  -0.07031881 -0.83560844]
step =  7 , state =  [ 0.12997631  0.37977495 -0.08703098 -0.56584282]
step =  8 , state =  [ 0.13757181  0.18597484 -0.09834783 -0.30179772]
step =  9 , state =  [ 0.14129131 -0.00761789 -0.10438379 -0.04167953]
step =  10 , state =  [ 0.14113895 -0.20110015 -0.10521738  0.21633103]
step =  11 , state =  [ 0.13711695 -0.39457289 -0.10089076  0.47405836]
step =  12 , state =  [ 0.12922549 -0.58813613 -0.09140959  0.73331517]
step =  13

step =  26 , state =  [ 0.0209442   1.35311417  0.02889256 -1.76093801]
step =  27 , state =  [ 0.04800648  1.54789749 -0.0063262  -2.04449782]
step =  28 , state =  [ 0.07896443  1.35284103 -0.04721616 -1.75377889]
step =  29 , state =  [ 0.10602125  1.15828531 -0.08229174 -1.47614693]
step =  30 , state =  [ 0.12918696  0.9642594  -0.11181468 -1.21025944]
step =  31 , state =  [ 0.14847215  0.77074455 -0.13601986 -0.95460489]
step =  32 , state =  [ 0.16388704  0.57768854 -0.15511196 -0.70756225]
step =  33 , state =  [ 0.17544081  0.38501663 -0.16926321 -0.46744442]
step =  34 , state =  [ 0.18314114  0.1926396  -0.1786121  -0.23252883]
step =  35 , state =  [ 0.18699393  0.00045956 -0.18326267 -0.00107798]
step =  36 , state =  [ 0.18700312 -0.19162581 -0.18328423  0.22864704]
step =  37 , state =  [ 0.18317061 -0.38372005 -0.17871129  0.45837778]
step =  38 , state =  [ 0.17549621 -0.57592528 -0.16954374  0.68983202]
step =  39 , state =  [ 0.1639777  -0.76833955 -0.15574709  0.92

step =  25 , state =  [ 0.01388836  1.20476691  0.05237319 -1.52103669]
step =  26 , state =  [ 0.0379837   1.3992183   0.02195246 -1.79692315]
step =  27 , state =  [ 0.06596807  1.5940878  -0.01398601 -2.08270347]
step =  28 , state =  [ 0.09784982  1.39911    -0.05564008 -1.79437714]
step =  29 , state =  [ 0.12583202  1.20465368 -0.09152762 -1.51949378]
step =  30 , state =  [ 0.1499251   1.01074969 -0.1219175  -1.25672681]
step =  31 , state =  [ 0.17014009  0.81738082 -0.14705203 -1.0045815 ]
step =  32 , state =  [ 0.18648771  0.62449628 -0.16714366 -0.76145495]
step =  33 , state =  [ 0.19897763  0.43202271 -0.18237276 -0.52567982]
step =  34 , state =  [ 0.20761809  0.23987221 -0.19288636 -0.29555483]
step =  35 , state =  [ 0.21241553  0.04794812 -0.19879745 -0.06936514]
step =  36 , state =  [ 0.21337449 -0.14385087 -0.20018476  0.15460482]
step =  37 , state =  [ 0.21049748 -0.33562774 -0.19709266  0.37806339]
step =  38 , state =  [ 0.20378492 -0.52748473 -0.18953139  0.60

step =  24 , state =  [ 0.05700774 -0.93361972 -0.06365048  1.30426473]
step =  25 , state =  [ 0.03833535 -1.12787935 -0.03756518  1.5763635 ]
step =  26 , state =  [ 0.01577776 -1.32253403 -0.00603791  1.85709796]
step =  27 , state =  [-0.01067292 -1.51758919  0.03110404  2.14790022]
step =  28 , state =  [-0.04102471 -1.32278683  0.07406205  1.86498115]
step =  29 , state =  [-0.06748044 -1.12854989  0.11136167  1.59617878]
step =  30 , state =  [-0.09005144 -0.93491061  0.14328525  1.34019175]
step =  31 , state =  [-0.10874965 -0.74185339  0.17008908  1.09555539]
step =  32 , state =  [-0.12358672 -0.54932941  0.19200019  0.86070211]
step =  33 , state =  [-0.13457331 -0.35726766  0.20921423  0.63400521]
step =  34 , state =  [-0.14171866 -0.16558291  0.22189434  0.41380904]
[-0.04745266  0.00095496  0.01409815 -0.01837518]
step =  0 , state =  [-0.04743356  0.19587192  0.01373065 -0.30657684]
step =  1 , state =  [-0.04351613  0.39079554  0.00759911 -0.59489804]
step =  2 , stat

step =  1 , state =  [ 0.03638292 -0.37798363 -0.01889708  0.56968293]
step =  2 , state =  [ 0.02882325 -0.57283552 -0.00750343  0.85635318]
step =  3 , state =  [ 0.01736654 -0.76785443  0.00962364  1.14666732]
step =  4 , state =  [ 0.00200945 -0.57285947  0.03255698  0.85701772]
step =  5 , state =  [-0.00944774 -0.37819587  0.04969734  0.57474712]
step =  6 , state =  [-0.01701165 -0.18380457  0.06119228  0.29812519]
step =  7 , state =  [-0.02068775  0.01039415  0.06715478  0.02535163]
step =  8 , state =  [-0.02047986  0.20449198  0.06766182 -0.2454102 ]
step =  9 , state =  [-0.01639002  0.39858558  0.06275361 -0.516007  ]
step =  10 , state =  [-0.00841831  0.59277032  0.05243347 -0.78827333]
step =  11 , state =  [ 0.0034371   0.78713438  0.03666801 -1.06401037]
step =  12 , state =  [ 0.01917978  0.98175229  0.0153878  -1.34496301]
step =  13 , state =  [ 0.03881483  1.17667737 -0.01151146 -1.63279218]
step =  14 , state =  [ 0.06234838  0.98169244 -0.0441673  -1.34371847]
s

step =  23 , state =  [ 0.1333311   0.41454036 -0.203774   -0.56578338]
step =  24 , state =  [ 0.1416219   0.22277203 -0.21508966 -0.34357827]
[ 0.012888   -0.03416887  0.00043767 -0.04922294]
step =  0 , state =  [ 0.01220462  0.1609468  -0.00054679 -0.34176775]
step =  1 , state =  [ 0.01542356 -0.03416737 -0.00738215 -0.04925729]
step =  2 , state =  [ 0.01474021 -0.22918269 -0.00836729  0.24108739]
step =  3 , state =  [ 0.01015656 -0.42418412 -0.00354555  0.53111934]
step =  4 , state =  [ 0.00167287 -0.61925602  0.00707684  0.82268297]
step =  5 , state =  [-0.01071225 -0.4242316   0.0235305   0.53223424]
step =  6 , state =  [-0.01919688 -0.22944838  0.03417519  0.24705761]
step =  7 , state =  [-0.02378585 -0.03483076  0.03911634 -0.03465281]
step =  8 , state =  [-0.02448246  0.15970906  0.03842328 -0.31474205]
step =  9 , state =  [-0.02128828  0.35426321  0.03212844 -0.59506421]
step =  10 , state =  [-0.01420302  0.54892111  0.02022716 -0.87745624]
step =  11 , state =  [-

step =  38 , state =  [-0.01410527 -1.70731298 -0.04161687  2.02594441]
step =  39 , state =  [-4.82515255e-02 -1.90198072e+00 -1.09798282e-03  2.30546136e+00]
step =  40 , state =  [-0.08629114 -2.0970926   0.04501124  2.59780619]
step =  41 , state =  [-0.12823299 -1.9023479   0.09696737  2.31921385]
step =  42 , state =  [-0.16627995 -1.70823299  0.14335165  2.05787306]
step =  43 , state =  [-0.20044461 -1.51483744  0.18450911  1.81275648]
step =  44 , state =  [-0.23074136 -1.32218826  0.22076424  1.58262604]
[ 0.00071226  0.02734932 -0.01613917  0.02206462]
step =  0 , state =  [ 0.00125925 -0.1675375  -0.01569788  0.30961208]
step =  1 , state =  [-0.0020915  -0.36243232 -0.00950563  0.59730329]
step =  2 , state =  [-0.00934015 -0.55741997  0.00244043  0.88697694]
step =  3 , state =  [-0.02048855 -0.36233123  0.02017997  0.59506219]
step =  4 , state =  [-0.02773517 -0.16749744  0.03208121  0.30880353]
step =  5 , state =  [-0.03108512  0.02715306  0.03825729  0.02640826]
step

step =  31 , state =  [-0.19461779 -1.17275685  0.16197708  1.51016034]
step =  32 , state =  [-0.21807292 -0.97992562  0.19218029  1.27211292]
step =  33 , state =  [-0.23767143 -0.787704    0.21762255  1.04524251]
[ 0.03577995 -0.00605198 -0.03235331 -0.01815526]
step =  0 , state =  [ 0.03565891 -0.20069537 -0.03271642  0.26414682]
step =  1 , state =  [ 0.031645   -0.39533544 -0.02743348  0.54633378]
step =  2 , state =  [ 0.02373829 -0.59006142 -0.01650681  0.83024841]
step =  3 , state =  [ 1.19370613e-02 -7.84953896e-01  9.81626315e-05  1.11769452e+00]
step =  4 , state =  [-0.00376202 -0.58983323  0.02245205  0.82504238]
step =  5 , state =  [-0.01555868 -0.39502544  0.0389529   0.5395047 ]
step =  6 , state =  [-0.02345919 -0.2004721   0.04974299  0.25934531]
step =  7 , state =  [-0.02746863 -0.00609426  0.0549299  -0.01724239]
step =  8 , state =  [-0.02759052  0.18819866  0.05458505 -0.29210094]
step =  9 , state =  [-0.02382654  0.38250156  0.04874303 -0.56708116]
step =  

step =  15 , state =  [ 0.00394526  1.18505384  0.01909008 -1.58724275]
step =  16 , state =  [ 0.02764633  1.3799438  -0.01265478 -1.87391228]
step =  17 , state =  [ 0.05524521  1.18496225 -0.05013302 -1.58518378]
step =  18 , state =  [ 0.07894445  0.99047097 -0.0818367  -1.30854632]
step =  19 , state =  [ 0.09875387  0.79647574 -0.10800763 -1.0425605 ]
step =  20 , state =  [ 0.11468339  0.602941   -0.12885884 -0.78564257]
step =  21 , state =  [ 0.12674221  0.40980266 -0.14457169 -0.53611672]
step =  22 , state =  [ 0.13493826  0.21697776 -0.15529402 -0.29225294]
step =  23 , state =  [ 0.13927782  0.02437158 -0.16113908 -0.05229353]
step =  24 , state =  [ 0.13976525 -0.16811707 -0.16218495  0.18552882]
step =  25 , state =  [ 0.13640291 -0.36059183 -0.15847437  0.42297853]
step =  26 , state =  [ 0.12919107 -0.55315553 -0.1500148   0.66180791]
step =  27 , state =  [ 0.11812796 -0.74590702 -0.13677865  0.90374881]
step =  28 , state =  [ 0.10320982 -0.93893779 -0.11870367  1.15

step =  30 , state =  [ 0.07549024  0.54358006 -0.1290413  -0.83112473]
step =  31 , state =  [ 0.08636185  0.35043558 -0.1456638  -0.58164974]
step =  32 , state =  [ 0.09337056  0.15762257 -0.15729679 -0.33816699]
step =  33 , state =  [ 0.09652301 -0.03495225 -0.16406013 -0.09892575]
step =  34 , state =  [ 0.09582396 -0.22738928 -0.16603865  0.13783623]
step =  35 , state =  [ 0.09127618 -0.41979202 -0.16328192  0.37387985]
step =  36 , state =  [ 0.08288034 -0.61226369 -0.15580433  0.61095542]
step =  37 , state =  [ 0.07063506 -0.80490426 -0.14358522  0.85079473]
step =  38 , state =  [ 0.05453698 -0.99780722 -0.12656932  1.09510238]
step =  39 , state =  [ 0.03458083 -1.19105568 -0.10466727  1.34554421]
step =  40 , state =  [ 0.01075972 -1.38471735 -0.07775639  1.60373094]
step =  41 , state =  [-0.01693463 -1.57883786 -0.04568177  1.87119455]
step =  42 , state =  [-0.04851138 -1.77343188 -0.00825788  2.1493553 ]
step =  43 , state =  [-0.08398002 -1.96847165  0.03472923  2.43

step =  13 , state =  [ 0.0357038   1.18025195 -0.02027671 -1.68261141]
step =  14 , state =  [ 0.05930884  0.98537058 -0.05392894 -1.39631038]
step =  15 , state =  [ 0.07901625  0.79095935 -0.08185514 -1.12096492]
step =  16 , state =  [ 0.09483544  0.59700072 -0.10427444 -0.85503967]
step =  17 , state =  [ 0.10677546  0.4034426  -0.12137523 -0.59688065]
step =  18 , state =  [ 0.11484431  0.21020949 -0.13331285 -0.34476016]
step =  19 , state =  [ 0.1190485   0.01721095 -0.14020805 -0.09690905]
step =  20 , state =  [ 0.11939272 -0.17565214 -0.14214623  0.14846047]
step =  21 , state =  [ 0.11587967 -0.36848272 -0.13917702  0.39313868]
step =  22 , state =  [ 0.10851002 -0.56138362 -0.13131425  0.63890607]
step =  23 , state =  [ 0.09728235 -0.75445385 -0.11853613  0.88752257]
step =  24 , state =  [ 0.08219327 -0.94778474 -0.10078568  1.14071589]
step =  25 , state =  [ 0.06323758 -1.14145532 -0.07797136  1.40016671]
step =  26 , state =  [ 0.04040847 -1.3355264  -0.04996802  1.66

step =  9 , state =  [ 0.08006183 -0.43007893 -0.06078037  0.53871784]
step =  10 , state =  [ 0.07146025 -0.62429611 -0.05000601  0.81164724]
step =  11 , state =  [ 0.05897433 -0.81869869 -0.03377307  1.08819094]
step =  12 , state =  [ 0.04260036 -1.01335942 -0.01200925  1.37008814]
step =  13 , state =  [ 0.02233317 -1.20832909  0.01539251  1.65899092]
step =  14 , state =  [-0.00183341 -1.01338991  0.04857233  1.371142  ]
step =  15 , state =  [-0.02210121 -0.81890795  0.07599517  1.09403778]
step =  16 , state =  [-0.03847937 -0.62486488  0.09787593  0.82613433]
step =  17 , state =  [-0.05097667 -0.43120791  0.11439861  0.56576875]
step =  18 , state =  [-0.05960083 -0.23786102  0.12571399  0.31120398]
step =  19 , state =  [-0.06435805 -0.04473336  0.13193807  0.06066126]
step =  20 , state =  [-0.06525272  0.14827434  0.13315129 -0.18765674]
step =  21 , state =  [-0.06228723  0.34126488  0.12939816 -0.43554923]
step =  22 , state =  [-0.05546193  0.53434037  0.12068717 -0.684